name: afrv1
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.3
  email_validator: ^2.1.17
  #cwc_flutter: ^1.0.0
  flutter_survey: ^0.1.4
  form_field_validator: ^1.1.0
  form_validation: ^2.2.0+6
  flutter_datetime_picker: ^1.5.1
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1
  printing: 5.6.3
  excel: 2.1.0
  table_calendar: ^3.0.9
  http: ^0.13.3
  image_picker: 0.8.3
  get: 4.3.2
  get_storage: ^2.1.0
  pdf: ^3.6.0
  open_file: ^3.0.3
  firebase_database: ^10.2.3
  firebase_core: ^2.13.0
  cloud_firestore: ^4.8.1
  fl_chart: ^0.61.0
  file_picker: ^4.5.1
  firebase_storage: ^11.2.3
  uuid: ^3.0.7
  firebase_auth: ^4.6.3
  signature: ^5.0.0
  shared_preferences: ^2.2.0
  firebase_crashlytics: ^3.3.3
  flutter_native_splash: ^2.2.1
  file_picker_cross: ^4.4.0
  webview_flutter: ^2.0.13
  universal_html: ^2.2.2
  simple_animations: ^4.0.0
  flutter_form_builder: ^7.0.0
  logger: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "F6B456"
  image: assets/images/logo1LOG.png
  icon_background_color: "ffffff"
  ios: true
  android: true
  web: true


dependency_overrides:
  collection: ^1.15.0
  intl: ^0.17.0
  firebase_core_platform_interface: 4.8.0
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/1logicsticswhite.jpeg
    - assets/images/flowphoto.png
    - assets/images/ffdb7b09281029297629c7caa5123458.png
    - assets/images/pngwing.com (26).png
    - assets/images/pngwing.com (27).png
    - assets/images/pngwing.com (28).png
    - assets/images/logo1LOG.png
    - assets/images/backgroundONELOG.png
    - assets/images/profile.png
    - assets/images/safetylogo.png
    - assets/images/dailyfinding.jpeg
    - assets/images/perodua.png
    - assets/images/circle.png
    - assets/images/triangle.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages